### ISSUE TITLE
Can you provide instructions on how to run the unit tests?

### ISSUE THREAD

**Issue by ghv** [facebook/device-year-class#10]
I opened the project in Android Studio and tried all the ways of running the tests with no luck.
Is there some special trick?

**Comment by rrong** [comment]
The unit tests are run with Gradle.
You can run them with 'gradle cleanTest test' or create a build configuration yourself.

Android Studio should be able to automatically create the build configuration if you go to YearClassTest.java -> right click -> Create Run Configuration -> YearClassTest (pick the Gradle configuration)

If that doesn't work you can create one manually. Here's what mine looks like:
![screen shot 2015-04-08 at 16 22 52](https://cloud.githubusercontent.com/assets/2607783/7057545/8b32dd08-de0b-11e4-9bca-7e83661f5a55.png)

**Comment by ghv** [comment]
Thank you for the instructions. I was able to create and run the configuration as you described, but when I run the test, it builds the `cleanTest` and `test` tasks without errors, but then says "Test events were not received" in the Run tab. Could I missing a plugin to run these tests? 

I was using AS 1.2. If I try AS 1.1 I get a warning to use Android Gradle plugin 1.1 or newer in order to run unit tests. Trying the newer plugin fails during the Gradle sync with an error about not being able to add a `testCompile` configuration because it already exists while applying the roboelectric plugin. Furthermore, trying it without changes to the plugin version, it just assembles the unit test package and still not running the tests.

**Comment by rrong** [comment]
I tried running with AS 1.2, and got the same error as you. For now I'd advise sticking to AS 1.1.

However, I'm not sure where you're getting your errors from: I'm running the tests on AS 1.1 and Gradle plugin 1.0.0 and it seems to work fine. Are you sure it's not running the tests? A quick way to test this is to change one of the asserts in a unit test and see if that causes your test run to fail.

There does seem to be some issue between older versions of robolectric and Gradle 1.1.0. If you want to upgrade to Gradle 1.1.0, I'd suggest upgrading to the latest version of robolectric as well. Change ` classpath 'org.robolectric:robolectric-gradle-plugin:0.14.+'` to `classpath 'org.robolectric:robolectric-gradle-plugin:1.0.1'` in device-year-class/build.gradle, and replace instances of `apply plugin: 'robolectric'` with `apply plugin: 'org.robolectric'`.

I'm currently looking into the best way to upgrade the unit testing framework, I'll push an update to it very soon.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by SeyelentEco** [comment]
Sorry for the delay, I looked into it and realized our plugin was out of date.  I fixed the issues and now you can run the tests using the normal Android Studio way or gradlew.

You can see the details of how to run the unit tests here:
https://developer.android.com/training/testing/unit-testing/local-unit-tests.html
