### ISSUE TITLE
Year class for Nexus 6P is 2013?

### ISSUE THREAD

**Issue by dustedrob** [facebook/device-year-class#25]
I get 2013 for the Nexus 6p which is clearly wrong since this device was considered high end in 2015 and 2016. I'm using the latest Android 7.1 dev preview.

It's also weird because for a Samsung S6 which has similar specs, i get 2014 which is more reasonable but should really be 2015. The Samsung is running on Android 6 which makes me think there's something wrong with Android 7.

**Comment by aaronbond** [comment]
my redmi note 3 pro is too, seems because it's 1.8ghz, not matter how powerful it is if the cpu is not 2.0ghz and above it does not get the 2014 rating even though this phone would certainly blow away high end phones of that year.

**Comment by santhoshvai** [comment]
Nexus 6p reports 2014 actually. Seems like since RAM is 3GB it reports 2014.

**Comment by zlern2k** [comment]
Under the 2.x definitions, RAM dominates the other characteristics.
Nexus 6p has 3GB => YC2014.
Redmi Note 3 Pro also has 3GB => YC2014
