### ISSUE TITLE
Why doing  & 0x01?

### ISSUE THREAD

**Issue by Macarse** [facebook/device-year-class#3]
I noticed you guys are using:

```
if ((componentYears.size() & 0x01) == 1) {  // Odd number; pluck the median.
```

Why not using `%` directly?

**Comment by zlern2k** [comment]
You're proposing using `(componentYears.size() % 2 == 1)` instead, right?

In my mind, using the bitmask connotes that I just care about even vs. odd, while % makes me think about the divisor. I suspect they compile to the same or at least very similar JVM instructions.

You can find more opinions at http://stackoverflow.com/questions/7342237/check-whether-number-is-even-or-odd.
